# Generated by Django 5.2 on 2025-12-14 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_email_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxWorkerQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tax_worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.taxworkerprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'tax_worker')},
            },
        ),
    ]
