# Generated by Django 5.2 on 2025-12-14 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_taxworkerquestion'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='taxworkerquestion',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='taxworkerquestion',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taxworkerquestion',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asked_questions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taxworkerquestion',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('answered', 'Answered')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='taxworkerquestion',
            name='tax_worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_questions', to='users.taxworkerprofile'),
        ),
        migrations.RemoveField(
            model_name='taxworkerquestion',
            name='user',
        ),
    ]
