# Generated by Django 5.2 on 2025-12-14 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_taxworkerquestion_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxworkerquestion',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asked_questions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='taxworkerquestion',
            name='tax_worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_questions', to='users.taxworkerprofile'),
        ),
    ]
