# Generated by Django 5.2 on 2025-12-14 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_instructorcoursepurchase_transitorrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorprofile',
            name='course_material',
            field=models.FileField(blank=True, null=True, upload_to='course_materials/'),
        ),
        migrations.AddField(
            model_name='taxworkerquestion',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='taxworkerquestion',
            name='receipt',
            field=models.FileField(default='receipts/placeholder.pdf', upload_to='receipts/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transitorrequest',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='transitorrequest',
            name='receipt',
            field=models.FileField(default='receipts/placeholder.pdf', upload_to='receipts/'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='InstructorRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.instructorprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'instructor')},
            },
        ),
        migrations.CreateModel(
            name='TaxWorkerRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tax_worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.taxworkerprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'tax_worker')},
            },
        ),
        migrations.CreateModel(
            name='TransitorRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.transitorprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'transitor')},
            },
        ),
    ]
