# Generated by Django 5.2 on 2025-12-15 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_communityquestion_communityanswer_supportticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='answered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
