# Generated by Django 5.2 on 2025-12-26 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_taxworkerprofile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeitem',
            name='enhancement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storeitem',
            name='size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
